// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type PostInput struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Content     string    `json:"content"`
	UserID      string    `json:"user_id"`
	Tags        []*string `json:"tags"`
}
